# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Validate API Spec with API Governance
        run: echo "anypoint-cli governance api validate" 
        
      - name: Compile or Build App
        run: echo "mvn clean package"
        
      - name: Run Unit Tests & Generate Report
        run: echo "mvn clean test && mvn test coverage"
        
      - name: Deploy to Cloudhub 2
        run: echo "mvn clean deploy -DmuleDeploy"
        
      - name: Run Integration & Performance & Security Test
        run: echo "bat integration-tests.dwl"
